# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xp3rGRTeiH8Xce7EUNkiSL0FcGxKxUix
"""



import asyncio
import logging
import sqlite3
from aiogram import Bot, Dispatcher, types
from aiogram.filters.command import Command
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
import urllib.parse

logging.basicConfig(level=logging.INFO)
bot = Bot(token="8512046766:AAHxe87psQLRhEjv2zcgzm86cwayeX4YR9E")
dp = Dispatcher()


data = sqlite3.connect('cars.db')
cursor = data.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY,
    year TEXT,
    brand TEXT
)
''')
data.commit()

button1 = KeyboardButton(text="Моя машина")
button2 = KeyboardButton(text="Ближайший сервис")
button3 = KeyboardButton(text="Вызвать эвакуатор")
button4 = KeyboardButton(text="Ближайший авто-магазин")
button5 = KeyboardButton(text="Купить/продать авто")
button6 = KeyboardButton(text="Жалобы/Помощь")

keyboard = ReplyKeyboardMarkup(
    keyboard=[[button1], [button2, button3], [button4], [button5], [button6]],
    resize_keyboard=True
)


geo_button = KeyboardButton(text="📍 Отправить геолокацию", request_location=True)
location_state = {}

@dp.message(Command("start"))
async def cmd_start(message: types.Message):
    await message.answer("Выберите один из них:", reply_markup=keyboard)

@dp.message()
async def handle(message: types.Message):
    user = message.from_user.id

    if message.text == "Моя машина":
        cursor.execute("SELECT year, brand FROM users WHERE user_id = ?", (user,))
        car_data = cursor.fetchone()

        if car_data and car_data[0] and car_data[1]:
            await message.answer(f"Ваша машина: {car_data[1]} {car_data[0]}")
        else:
            await message.answer("Укажите год выпуска:")
            location_state[user] = "year"

    elif message.text == "Ближайший сервис":
        await message.answer("Отправьте вашу геолокацию:", reply_markup=ReplyKeyboardMarkup(
            keyboard=[[geo_button]], resize_keyboard=True
        ))
        location_state[user] = "service"

    elif message.text == "Ближайший авто-магазин":
        await message.answer("Отправьте вашу геолокацию:", reply_markup=ReplyKeyboardMarkup(
            keyboard=[[geo_button]], resize_keyboard=True
        ))
        location_state[user] = "shop"

    elif user in location_state and location_state[user] == "year":
        cursor.execute("INSERT OR REPLACE INTO users (user_id, year) VALUES (?, ?)", (user, message.text))
        data.commit()
        await message.answer("Марка вашей машины:")
        location_state[user] = "brand"

    elif user in location_state and location_state[user] == "brand":
        cursor.execute("UPDATE users SET brand = ? WHERE user_id = ?", (message.text, user))
        data.commit()
        await message.answer(f"Сохранено: {message.text}")
        del location_state[user]
        await message.answer("Выберите действие:", reply_markup=keyboard)

    elif message.location:
        lat = message.location.latitude
        lon = message.location.longitude

        search_type = location_state.get(user)

        if search_type == "service":
            query = "автосервис"
            answer_text = " Ближайшие автосервисы"
        elif search_type == "shop":
            query = "автомагазин"
            answer_text = " Ближайшие автомагазины"
        else:
            await message.answer("Сначала выберите 'Ближайший сервис' или 'Ближайший авто-магазин'", reply_markup=keyboard)
            return

        yandex_url = f"https://yandex.ru/maps/?text={urllib.parse.quote(query)}&ll={lon},{lat}&z=15"

        await message.answer(
            f"{answer_text}:\n[Открыть в Яндекс.Картах]({yandex_url})",
            parse_mode="Markdown",
            reply_markup=keyboard
        )

        if user in location_state:
            del location_state[user]

    elif message.text == "Вызвать эвакуатор":
        await message.answer(" Для вызова эвакуатора позвоните: +79669936595")

    elif message.text == "Купить/продать авто":
        await message.answer(" Рекомендуем сайты: Auto.ru")

    elif message.text == "Жалобы/Помощь":
        await message.answer(" Свяжитесь с поддержкой: @dilmuhammad9")

async def main():
    await dp.start_polling(bot)
await main()
